import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import {
  applyLocalFoldOperations,
  createCreasePatternSvg,
  createDiagramSequence,
  createDiagramStep,
  createPreviewAnimation,
  createPreviewModel,
  loadFoldFile,
  serializeFold,
  stableStringify,
  validateExecutorReadableStep,
  validateFold
} from "../../fold-core/src/index.mjs";

import {
  buildExternalValidationStatus,
  checkCommunityFoldArtifact,
  createFlatFolderStateArtifact,
  getExecutorVisualMetadata,
  validateFlatFolderArtifact
} from "./community-adapters.mjs";
import { createOrigamiSimulatorExport, summarizeCommunityPreview } from "./community-preview.mjs";
import { createDisplayDecision } from "./display-decision.mjs";
import { writeExecutorOverlayArtifacts } from "./executor-overlays.mjs";
import { createFoldProgramIr, createVisualWalkthrough } from "./fold-program-ir.mjs";
import { createSourceProvenance } from "./source-provenance.mjs";
import { createStepStateArtifacts } from "./step-states.mjs";
import { evaluateTargetMatch } from "./target-match.mjs";

export const stage1ExecutorProfiles = ["human-hand", "two-finger-gripper", "cat-paw-profile", "dog-paw-profile"];
export const stage1SimpleTargetFiles = [
  "simple-bird.svg",
  "simple-fish.svg",
  "simple-flower.svg",
  "simple-boat.svg",
  "simple-star.svg"
];
export const defaultPipelineTargetFiles = [
  "known-good-triangle.svg",
  "known-good-corner.svg",
  "known-good-paper-hat.svg",
  "known-good-square-packet.svg",
  "generated-triangle.svg",
  "simple-fish.svg",
  "simple-bird.svg",
  "simple-flower.svg",
  "simple-boat.svg",
  "simple-star.svg"
];

export const targetProfiles = {
  "known-good-triangle.svg": {
    caseId: "known-good-triangle",
    baseForm: "bird-base.fold",
    targetFeatures: ["triangle", "solver-backed", "single folded silhouette"],
    candidates: [
      sequenceCandidate("known-good-triangle-sequence", "Fold into a solver-backed triangle", [
        operation("triangle-side-collapse", "Collapse the side panel into a triangle", "V", [1, 4], "Uses a solver-passing side collapse that matches the triangle target silhouette.")
      ], 0.91, "Known-good Flat-Folder passing triangle silhouette.")
    ]
  },
  "known-good-corner.svg": {
    caseId: "known-good-corner",
    baseForm: "bird-base.fold",
    targetFeatures: ["corner fold", "solver-backed", "single folded silhouette"],
    candidates: [
      sequenceCandidate("known-good-corner-sequence", "Fold into a solver-backed corner form", [
        operation("corner-panel-fold", "Fold the left corner panel", "F", [0, 4], "Uses a solver-passing corner fold that matches the corner target silhouette.")
      ], 0.9, "Known-good Flat-Folder passing corner silhouette.")
    ]
  },
  "known-good-paper-hat.svg": {
    caseId: "known-good-paper-hat",
    baseForm: "bird-base.fold",
    targetFeatures: ["paper hat", "cone silhouette", "solver-backed", "single folded silhouette"],
    candidates: [
      sequenceCandidate("known-good-paper-hat-sequence", "Fold into a solver-backed paper hat cone", [
        operation("paper-hat-cone-collapse", "Collapse the side panel into a paper hat cone", "V", [1, 4], "Uses a solver-passing cone silhouette with decorative target lines that do not drive the geometry gate.")
      ], 0.91, "Known-good Flat-Folder passing paper hat silhouette.")
    ]
  },
  "known-good-square-packet.svg": {
    caseId: "known-good-square-packet",
    baseForm: "bird-base.fold",
    targetFeatures: ["square packet", "two step tutorial", "solver-backed", "full intermediate states"],
    candidates: [
      sequenceCandidate("known-good-square-packet-sequence", "Fold a two-step square packet", [
        operation("square-packet-first-corner", "Fold the first packet corner", "F", [0, 4], "First solver-passing packet corner state."),
        operation("square-packet-second-corner", "Fold the second packet corner", "F", [1, 4], "Second solver-passing packet corner state; every prefix remains backend-backed.")
      ], 0.92, "Known-good two-step Flat-Folder passing square packet tutorial.")
    ]
  },
  "generated-triangle.svg": {
    caseId: "generated-triangle",
    baseForm: "bird-base.fold",
    targetFeatures: ["generated candidate", "triangle", "solver-backed", "single folded silhouette"],
    generator: {
      id: "deterministic-local-fold-search-v1",
      version: "v1",
      seed: "phase-16-generated-triangle",
      operation_library_id: "single-edge-collapse-library-v1",
      search_policy: "rank locally valid fold operations, then graduate only through backend state and target-match gates"
    },
    candidates: [
      generatedSequenceCandidate("generated-triangle-sequence", "Generate a solver-backed triangle candidate", [
        operation("generated-triangle-side-collapse", "Generate side collapse for triangle", "V", [1, 4], "Generated by deterministic local search from the single-edge collapse operation library.")
      ], 0.905, "Generated candidate that must pass solver, target, step, and executor gates before display."),
      generatedSequenceCandidate("generated-triangle-wrong-corner", "Generate a wrong-target corner candidate", [
        operation("generated-triangle-corner-decoy", "Generate corner decoy fold", "F", [0, 4], "Solver-valid negative candidate kept as rejected evidence because it does not best match the generated target.")
      ], 0.72, "Solver-valid decoy candidate; lower ranked and not allowed to drive completed display.")
    ]
  },
  "simple-bird.svg": {
    caseId: "simple-bird",
    baseForm: "bird-base.fold",
    targetFeatures: ["wings", "beak", "upright silhouette"],
    candidates: [
      sequenceCandidate("bird-wing-beak-sequence", "Add wing and beak folds", [
        operation("bird-centerline-wing", "Add a centerline wing valley", "V", [5, 6], "Adds a broad wing crease across the bird base."),
        operation("bird-diagonal-beak", "Sharpen the beak diagonal", "M", [0, 2], "Reuses the diagonal to emphasize a beak-like point."),
        operation("bird-tail-counterfold", "Set a tail counterfold", "V", [1, 3], "Adds a counter crease so the tail reads separately from the wings.")
      ], 0.86, "Combines a broad wing crease with a diagonal beak cue."),
      candidate("bird-centerline-wing", "Add a centerline wing valley", "V", [5, 6], 0.82, "Adds a broad wing crease across the bird base."),
      invalidCandidate("bird-overextended-tail")
    ]
  },
  "simple-fish.svg": {
    caseId: "simple-fish",
    baseForm: "fish-base.fold",
    targetFeatures: ["tail", "body", "horizontal silhouette"],
    candidates: [
      sequenceCandidate("fish-tail-body-sequence", "Add tail and body folds", [
        operation("fish-tail-centerline", "Add a tail centerline valley", "V", [5, 6], "Adds a tail/body separation crease to the fish base."),
        operation("fish-body-diagonal", "Bias the body diagonal", "M", [0, 2], "Keeps a simple asymmetric body cue."),
        operation("fish-fin-cross-crease", "Lift a small fin crease", "V", [1, 3], "Adds a secondary fin cue across the fish body."),
        operation("fish-nose-flatten", "Flatten the nose guide", "F", [2, 4], "Softens the front point into a readable head guide.")
      ], 0.87, "Combines tail separation with a body diagonal."),
      candidate("fish-tail-centerline", "Add a tail centerline valley", "V", [5, 6], 0.84, "Adds a tail/body separation crease to the fish base."),
      invalidCandidate("fish-overextended-fin")
    ]
  },
  "simple-flower.svg": {
    caseId: "simple-flower",
    baseForm: "waterbomb-base.fold",
    targetFeatures: ["petals", "radial symmetry", "center"],
    candidates: [
      sequenceCandidate("flower-petal-cross-sequence", "Add petal and cross folds", [
        operation("flower-petal-centerline", "Add a petal centerline valley", "V", [5, 6], "Adds a simple petal split while preserving radial structure."),
        operation("flower-cross-diagonal", "Reinforce flower diagonal", "M", [1, 3], "Uses a crossing diagonal as a second petal cue."),
        operation("flower-second-diagonal", "Open the opposite petal diagonal", "V", [0, 2], "Balances the flower with a second diagonal petal guide."),
        operation("flower-center-lock", "Press the center lock", "M", [0, 4], "Emphasizes the flower center without changing the outer boundary."),
        operation("flower-petal-soften", "Soften the petal rim", "F", [2, 4], "Marks a soft rim fold for the upper petal.")
      ], 0.85, "Combines midpoint and cross-diagonal petal cues."),
      candidate("flower-petal-centerline", "Add a petal centerline valley", "V", [5, 6], 0.8, "Adds a simple petal split while preserving radial structure."),
      invalidCandidate("flower-outside-paper")
    ]
  },
  "simple-boat.svg": {
    caseId: "simple-boat",
    baseForm: "kite-base.fold",
    targetFeatures: ["sail", "hull", "mast"],
    candidates: [
      sequenceCandidate("boat-mast-hull-sequence", "Add mast and hull folds", [
        operation("boat-mast-centerline", "Add a mast centerline valley", "V", [5, 6], "Creates a strong mast-like vertical reference in the kite base."),
        operation("boat-hull-diagonal", "Tilt hull diagonal", "M", [0, 2], "Keeps a hull-like diagonal cue for the lower shape."),
        operation("boat-sail-balance", "Balance the sail fold", "V", [1, 3], "Adds a second sail guide for a clearer mast and hull separation."),
        operation("boat-keel-press", "Press the keel guide", "M", [3, 4], "Adds a short keel cue along the lower panel.")
      ], 0.86, "Combines a mast centerline with a hull diagonal cue."),
      candidate("boat-mast-centerline", "Add a mast centerline valley", "V", [5, 6], 0.83, "Creates a strong mast-like vertical reference in the kite base."),
      invalidCandidate("boat-overextended-sail")
    ]
  },
  "simple-star.svg": {
    caseId: "simple-star",
    baseForm: "frog-base.fold",
    targetFeatures: ["points", "radial folds", "center"],
    candidates: [
      sequenceCandidate("star-point-cross-sequence", "Add point and cross folds", [
        operation("star-point-centerline", "Add a point centerline valley", "V", [5, 6], "Adds a symmetric point split to the frog base."),
        operation("star-cross-diagonal", "Reinforce star diagonal", "M", [1, 3], "Adds a crossing fold useful for a point-like silhouette.")
      ], 0.84, "Combines a symmetric point split with a cross-diagonal point cue."),
      candidate("star-point-centerline", "Add a point centerline valley", "V", [5, 6], 0.78, "Adds a symmetric point split to the frog base."),
      invalidCandidate("star-outside-paper")
    ]
  }
};

export async function runCuratedPipeline(options = {}) {
  const baseFormsDir = options.baseFormsDir ?? "benchmarks/base-forms";
  const targetsDir = options.targetsDir ?? "benchmarks/targets";
  const outDir = options.outDir ?? "out/m2-pipeline";
  const targetFiles = options.targetFiles ?? defaultPipelineTargetFiles;
  const metadata = JSON.parse(await readFile(join(targetsDir, "metadata.json"), "utf8"));
  const targets = selectTargets(metadata.targets, targetFiles);

  if (targets.length < 5) {
    throw new Error(`pipeline requires at least five curated targets, found ${targets.length}`);
  }

  await mkdir(outDir, { recursive: true });

  const cases = [];
  for (const target of targets) {
    cases.push(await runTargetCase({ target, profile: targetProfiles[target.file], baseFormsDir, targetsDir, outDir }));
  }

  const completedCases = cases.filter((pipelineCase) => pipelineCase.status === "valid");
  const completedUsableCases = cases.filter((pipelineCase) => pipelineCase.display_mode === "completed-usable");
  const completedUsableGeneratedCases = cases.filter((pipelineCase) => pipelineCase.display_mode === "completed-usable-generated");
  const simulatorValid = cases.length >= 5 && cases.every((pipelineCase) => pipelineCase.status === "valid" && pipelineCase.claim_status.simulator_valid === true);
  const executorReadable = cases.length >= 5 && cases.every((pipelineCase) => pipelineCase.executor_readable === true);
  const summary = {
    milestone: "M2",
    ok: cases.length >= 5 && executorReadable,
    case_count: cases.length,
    completed_case_count: completedCases.length,
    completed_usable_case_count: completedUsableCases.length,
    completed_usable_generated_case_count: completedUsableGeneratedCases.length,
    completed_3d_partial_walkthrough_case_count: cases.filter((pipelineCase) => pipelineCase.display_mode === "completed-3d-partial-walkthrough").length,
    blocked_case_count: cases.filter((pipelineCase) => pipelineCase.status !== "valid").length,
    claim_status: buildClaimStatus({ simulatorValid, executorReadable }),
    cases
  };
  await writeJson(join(outDir, "summary.json"), summary);
  return summary;
}

async function runTargetCase({ target, profile, baseFormsDir, targetsDir, outDir }) {
  const caseDir = join(outDir, profile.caseId);
  await mkdir(caseDir, { recursive: true });
  await readFile(join(targetsDir, target.file), "utf8");

  const baseFold = await loadFoldFile(join(baseFormsDir, profile.baseForm));
  const records = profile.candidates.map((candidateConfig, index) => buildCandidateRecord(baseFold, candidateConfig, index));
  const selected = selectBestValidCandidate(records);
  const proposalHistory = buildProposalHistory(target, profile, records, selected);
  const criticHistory = buildCriticHistory(target, profile, records, selected);

  const artifactPaths = {
    proposal_history: artifactPath(join(caseDir, "proposal-history.json")),
    critic_history: artifactPath(join(caseDir, "critic-history.json")),
    case_summary: artifactPath(join(caseDir, "summary.json"))
  };

  let selectedValidation = { ok: false, errors: ["No valid candidate selected"], warnings: [] };
  let communityFoldValidation = null;
  let flatFolderValidation = null;
  let flatFolderState = null;
  let stepStates = null;
  let executorOverlays = null;
  let targetMatch = null;
  let communityPreview = null;
  let diagramStepValidation = { ok: false, errors: ["No executor-readable step emitted"] };
  let diagramProfileValidation = {};
  let executorReadable = false;
  if (selected) {
    selectedValidation = selected.validation;
    artifactPaths.derived_fold = artifactPath(join(caseDir, "derived.fold"));
    artifactPaths.crease_svg = artifactPath(join(caseDir, "crease.svg"));
    artifactPaths.validation = artifactPath(join(caseDir, "validation.json"));
    artifactPaths.source_provenance = artifactPath(join(caseDir, "source-provenance.json"));
    artifactPaths.community_fold_validation = artifactPath(join(caseDir, "community-fold-validation.json"));
    artifactPaths.flat_folder_validation = artifactPath(join(caseDir, "flat-folder-validation.json"));
    artifactPaths.flat_folder_state = artifactPath(join(caseDir, "flat-folder-state.json"));
    artifactPaths.folded_state_fold = artifactPath(join(caseDir, "folded-state.fold"));
    artifactPaths.target_match = artifactPath(join(caseDir, "target-match.json"));
    artifactPaths.display_decision = artifactPath(join(caseDir, "display-decision.json"));
    artifactPaths.origami_simulator_fold = artifactPath(join(caseDir, "origami-simulator.fold"));
    artifactPaths.origami_simulator_preview = artifactPath(join(caseDir, "origami-simulator-preview.json"));
    artifactPaths.diagram_step = artifactPath(join(caseDir, "diagram-step.json"));
    artifactPaths.diagram_sequence = artifactPath(join(caseDir, "diagram-sequence.json"));
    artifactPaths.diagram_sequences = {};
    artifactPaths.preview = artifactPath(join(caseDir, "preview.json"));
    artifactPaths.preview_animation = artifactPath(join(caseDir, "preview-animation.json"));
    artifactPaths.step_states = artifactPath(join(caseDir, "step-states.json"));
    artifactPaths.step_visuals = artifactPath(join(caseDir, "step-visuals.json"));
    artifactPaths.executor_overlays = artifactPath(join(caseDir, "executor-overlays", "executor-overlays.json"));
    artifactPaths.fold_program_ir = artifactPath(join(caseDir, "fold-program-ir.json"));
    artifactPaths.visual_walkthrough = artifactPath(join(caseDir, "visual-walkthrough.json"));
    if (isGeneratedCandidate(selected)) {
      artifactPaths.candidate_recipe = artifactPath(join(caseDir, "candidate-recipe.json"));
      artifactPaths.candidate_run = artifactPath(join(caseDir, "candidate-run.json"));
    }

    const profileSequences = Object.fromEntries(stage1ExecutorProfiles.map((executorProfile) => {
      const steps = selected.operations.map((operation, index) => createDiagramStep(operation, index + 1, {
        executorProfile,
        supportedExecutorProfiles: stage1ExecutorProfiles
      }));
      const sequence = {
        ...createDiagramSequence(steps, { executorProfile }),
        executor_visual_metadata: getExecutorVisualMetadata(executorProfile)
      };
      return [executorProfile, {
        steps,
        sequence,
        validation: steps.map((step) => validateExecutorReadableStep(step))
      }];
    }));
    const diagramStep = profileSequences["human-hand"].steps[0];
    const diagramSequence = profileSequences["human-hand"].sequence;
    diagramStepValidation = profileSequences["human-hand"].validation[0];
    diagramProfileValidation = Object.fromEntries(
      Object.entries(profileSequences).map(([executorProfile, value]) => [executorProfile, {
        ok: value.validation.every((result) => result.ok),
        steps: value.validation
      }])
    );
    executorReadable = selectedValidation.ok && Object.values(diagramProfileValidation).every((result) => result.ok);

    await writeFile(join(caseDir, "derived.fold"), serializeFold(selected.derived), "utf8");
    if (isGeneratedCandidate(selected)) {
      await writeJson(join(caseDir, "candidate-recipe.json"), createCandidateRecipeArtifact({
        target,
        profile,
        selected,
        records
      }));
    }
    communityFoldValidation = await checkCommunityFoldArtifact(join(caseDir, "derived.fold"));
    flatFolderValidation = await validateFlatFolderArtifact(join(caseDir, "derived.fold"), join(caseDir, "flat-folder-validation.json"));
    flatFolderState = await createFlatFolderStateArtifact(
      join(caseDir, "derived.fold"),
      join(caseDir, "flat-folder-state.json"),
      join(caseDir, "folded-state.fold")
    );
    targetMatch = await createTargetMatchArtifact({
      targetPath: join(targetsDir, target.file),
      foldedStatePath: join(caseDir, "folded-state.fold"),
      outputPath: join(caseDir, "target-match.json"),
      solverState: flatFolderState
    });
    communityPreview = await createOrigamiSimulatorExport(
      join(caseDir, "derived.fold"),
      join(caseDir, "origami-simulator.fold"),
      join(caseDir, "origami-simulator-preview.json")
    );
    await writeFile(join(caseDir, "crease.svg"), createCreasePatternSvg(selected.derived), "utf8");
    await writeJson(join(caseDir, "validation.json"), selected.validation);
    await writeJson(join(caseDir, "community-fold-validation.json"), communityFoldValidation);
    await writeJson(join(caseDir, "diagram-step.json"), diagramStep);
    await writeJson(join(caseDir, "diagram-sequence.json"), diagramSequence);
    for (const [executorProfile, value] of Object.entries(profileSequences)) {
      const fileName = `diagram-sequence-${executorProfile}.json`;
      artifactPaths.diagram_sequences[executorProfile] = artifactPath(join(caseDir, fileName));
      await writeJson(join(caseDir, fileName), value.sequence);
    }
    await writeJson(join(caseDir, "preview.json"), createPreviewModel(selected.derived));
    const previewAnimation = createPreviewAnimation(selected.derived);
    const externalValidation = buildExternalValidationStatus({
      foldCompatibility: communityFoldValidation,
      flatFolder: flatFolderValidation
    });
    externalValidation.community_preview = summarizeCommunityPreview(communityPreview);
    externalValidation.flat_folder_state = summarizeSolverState(flatFolderState);
    await writeJson(join(caseDir, "preview-animation.json"), previewAnimation);
    const completedTargetForStepStates = selectedValidation.ok
      && communityFoldValidation?.status === "passed"
      && flatFolderValidation?.status === "passed"
      && flatFolderState?.status === "passed"
      && targetMatch?.status === "passed";
    stepStates = await createStepStateArtifacts({
      caseDir,
      baseFold,
      operations: selected.operations,
      completedTarget: completedTargetForStepStates
    });
    const stepVisuals = createStepVisuals({
      caseId: profile.caseId,
      target,
      operations: selected.operations,
      animation: previewAnimation,
      sequence: profileSequences["human-hand"].sequence,
      profileSequences,
      stepStates
    });
    executorOverlays = await writeExecutorOverlayArtifacts({
      caseDir,
      caseId: profile.caseId,
      stepVisuals,
      executorProfiles: stage1ExecutorProfiles
    });
    await writeJson(join(caseDir, "step-visuals.json"), stepVisuals);
    const displayDecision = createDisplayDecision({
      caseId: profile.caseId,
      selected,
      selectedValidation,
      communityFoldValidation,
      flatFolderValidation,
      flatFolderState,
      targetMatch,
      stepStates,
      stepVisuals,
      executorOverlays,
      executorReadable,
      executorProfiles: stage1ExecutorProfiles,
      selectedExecutorProfile: "human-hand",
      artifactPaths
    });
    await writeJson(join(caseDir, "display-decision.json"), displayDecision);
    if (isGeneratedCandidate(selected)) {
      await writeJson(join(caseDir, "candidate-run.json"), createCandidateRunArtifact({
        target,
        profile,
        selected,
        selectedValidation,
        communityFoldValidation,
        flatFolderValidation,
        flatFolderState,
        targetMatch,
        stepStates,
        executorOverlays,
        displayDecision,
        artifactPaths
      }));
    }
    await writeJson(join(caseDir, "fold-program-ir.json"), createFoldProgramIr({
      caseId: profile.caseId,
      target,
      baseForm: profile.baseForm,
      baseFold,
      selected,
      artifactPaths,
      externalValidation
    }));
    const visualWalkthroughStatus = profile.caseId === "simple-bird" ? "walkthrough-complete" : "walkthrough-generated";
    await writeJson(join(caseDir, "visual-walkthrough.json"), createVisualWalkthrough({
      caseId: profile.caseId,
      target,
      fold: selected.derived,
      operations: selected.operations,
      executorProfile: "human-hand",
      sequence: profileSequences["human-hand"].sequence,
      animation: previewAnimation,
      status: visualWalkthroughStatus
    }));
  }

  const externalValidation = buildExternalValidationStatus({
    foldCompatibility: communityFoldValidation,
    flatFolder: flatFolderValidation
  });
  externalValidation.community_preview = summarizeCommunityPreview(communityPreview);
  externalValidation.flat_folder_state = flatFolderState ? summarizeSolverState(flatFolderState) : missingSolverState();
  externalValidation.target_match = targetMatch ? summarizeTargetMatch(targetMatch) : missingTargetMatch();
  externalValidation.step_states = stepStates ? summarizeStepStates(stepStates) : missingStepStates();
  externalValidation.executor_overlays = executorOverlays ? summarizeExecutorOverlays(executorOverlays) : missingExecutorOverlays();
  const displayDecision = selected
    ? JSON.parse(await readFile(join(caseDir, "display-decision.json"), "utf8"))
    : createDisplayDecision({
      caseId: profile.caseId,
      selected,
      selectedValidation,
      communityFoldValidation,
      flatFolderValidation,
      flatFolderState,
      targetMatch,
      stepStates,
      stepVisuals: null,
      executorOverlays,
      executorReadable,
      executorProfiles: stage1ExecutorProfiles,
      selectedExecutorProfile: "human-hand",
      artifactPaths
    });
  const completedTarget = selectedValidation.ok
    && communityFoldValidation?.status === "passed"
    && flatFolderValidation?.status === "passed"
    && flatFolderState?.status === "passed"
    && targetMatch?.status === "passed";
  const displayMode = displayDecision.display_mode;
  const resultQuality = buildResultQuality({ target, externalValidation, completedTarget, displayDecision });

  const caseSummary = {
    case_id: profile.caseId,
    target: {
      name: target.name,
      file: target.file
    },
    selected_base_form: profile.baseForm,
    status: completedTarget ? "valid" : selected ? "blocked" : "failed",
    status_reason: completedTarget
      ? "solver-backed-folded-state"
      : selected
        ? solverBlockedReason({ flatFolderValidation, flatFolderState, targetMatch })
        : "no-valid-local-candidate",
    display_mode: displayMode,
    display_decision: summarizeDisplayDecision(displayDecision),
    claim_status: buildClaimStatus({ simulatorValid: completedTarget, executorReadable }),
    result_quality: resultQuality,
    external_validation: externalValidation,
    fold_program_ir_status: selected ? "thin-ir" : "missing",
    visual_walkthrough_status: selected && profile.caseId === "simple-bird" ? "walkthrough-complete" : "walkthrough-generated",
    generated_candidate: isGeneratedCandidate(selected),
    generation_status: generatedStatusForDisplayMode(displayMode),
    executor_readable: executorReadable,
    executor_profile: "human-hand",
    executor_profiles: stage1ExecutorProfiles,
    diagram_step_validation: diagramStepValidation,
    diagram_profile_validation: diagramProfileValidation,
    selected_candidate_id: selected?.candidate_id ?? null,
    validation_status: selectedValidation.ok,
    candidate_count: records.length,
    rejected_candidate_count: records.filter((record) => !record.validation.ok).length,
    selected_operation_count: selected?.operations.length ?? 0,
    solver_backed_step_count: stepStates?.solver_backed_step_count ?? 0,
    step_state_status: stepStates?.status ?? "missing",
    candidate_operations: records.map((record) => ({
      candidate_id: record.candidate_id,
      operation_ids: record.operations.map((operation) => operation.id),
      operation_count: record.operations.length,
      validation_status: record.validation.ok ? "valid" : "invalid"
    })),
    artifact_paths: artifactPaths
  };

  await writeJson(join(caseDir, "source-provenance.json"), createSourceProvenance({
    pipelineCase: caseSummary,
    pipelineOutDir: outDir
  }));
  await writeJson(join(caseDir, "proposal-history.json"), proposalHistory);
  await writeJson(join(caseDir, "critic-history.json"), criticHistory);
  await writeJson(join(caseDir, "summary.json"), caseSummary);

  return caseSummary;
}

function buildCandidateRecord(baseFold, candidateConfig, index) {
  const operations = normalizeOperations(candidateConfig);
  const derived = applyLocalFoldOperations(baseFold, operations);
  const validation = validateFold(derived);
  return {
    rank: index + 1,
    candidate_id: candidateConfig.id,
    rationale: candidateConfig.rationale,
    operation: cloneJson(operations[0]),
    operations: cloneJson(operations),
    origin_kind: candidateConfig.origin_kind ?? "curated-profile-candidate",
    generator: cloneJson(candidateConfig.generator ?? null),
    score: validation.ok ? candidateConfig.score : 0,
    validation,
    derived
  };
}

function selectBestValidCandidate(records) {
  return records
    .filter((record) => record.validation.ok)
    .sort((a, b) => b.score - a.score || a.rank - b.rank)[0] ?? null;
}

function buildProposalHistory(target, profile, records, selected) {
  return {
    case_id: profile.caseId,
    target: {
      name: target.name,
      file: target.file
    },
    selected_base_form: profile.baseForm,
    strategy: "deterministic-curated-profile-v0",
    target_features: profile.targetFeatures,
    candidates: records.map((record) => ({
      rank: record.rank,
      candidate_id: record.candidate_id,
      selected: record.candidate_id === selected?.candidate_id,
      rationale: record.rationale,
      operation: record.operation,
      operations: record.operations,
      validation_status: record.validation.ok ? "valid" : "invalid",
      validation_errors: record.validation.errors
    }))
  };
}

function buildCriticHistory(target, profile, records, selected) {
  return {
    case_id: profile.caseId,
    target: {
      name: target.name,
      file: target.file
    },
    evaluator: "deterministic-validation-and-profile-score-v0",
    entries: records.map((record) => ({
      candidate_id: record.candidate_id,
      selected: record.candidate_id === selected?.candidate_id,
      validation_ok: record.validation.ok,
      score: record.score,
      verdict: record.validation.ok ? "ranked-valid" : "rejected-invalid",
      notes: record.validation.ok ? [record.rationale] : record.validation.errors
    }))
  };
}

function createStepVisuals({ caseId, target, operations, animation, sequence, profileSequences = null, stepStates = null }) {
  const frames = animation.frames.slice(1);
  const sequencesByProfile = normalizeStepVisualSequences(sequence, profileSequences);
  const profileSteps = Object.fromEntries(Object.entries(sequencesByProfile).map(([executorProfile, profileSequence]) => [
    executorProfile,
    operations.map((operation, index) => {
      const step = profileSequence.steps[index];
      const frame = frames[index] ?? animation.frames[0];
      return createStepVisual({
        operation,
        step,
        frame,
        stepNumber: index + 1,
        executorProfile,
        stepState: stepStates?.states?.[index] ?? null
      });
    })
  ]));
  const defaultSteps = profileSteps["human-hand"] ?? Object.values(profileSteps)[0] ?? [];
  const hasAllSolverBackedSteps = stepStates?.status === "complete";
  return {
    type: "foldgen.step_visuals.v1",
    case_id: caseId,
    display_source: hasAllSolverBackedSteps ? "flat-folder-step-state" : "mixed-step-state-and-inspection-preview",
    display_source_status: stepStates?.status === "complete"
      ? "solver-backed-post-states"
      : stepStates?.status === "partial"
        ? "partial-solver-backed-post-states"
        : "inspection-only-until-step-state-backend",
    step_state_artifact_path: stepStates?.output_path ?? null,
    solver_backed_step_count: stepStates?.solver_backed_step_count ?? 0,
    inspection_only_step_count: stepStates?.inspection_only_step_count ?? operations.length,
    target: {
      name: target.name,
      file: target.file
    },
    step_count: operations.length,
    annotation_legend: stepVisualLegend(),
    steps: defaultSteps,
    profile_steps: profileSteps
  };
}

function normalizeStepVisualSequences(sequence, profileSequences) {
  if (profileSequences) {
    return Object.fromEntries(Object.entries(profileSequences).map(([profile, value]) => [
      profile,
      value.sequence ?? value
    ]));
  }
  return {
    [sequence?.executor_profile ?? "human-hand"]: sequence
  };
}

function createStepVisual({ operation, step, frame, stepNumber, executorProfile, stepState = null }) {
  const preview = stepState?.folded_preview ?? frame.preview;
  const projected = projectPreviewVertices(preview.vertices, 360, 34);
  const executorOverlay = createExecutorOverlay({
    preview,
    projected,
    operation,
    executorProfile
  });
  return {
    step: step?.step ?? stepNumber,
    operation_id: operation.id,
    title: operation.name,
    assignment: operation.assignment,
    edge: operation.edge,
    executor_profile: executorProfile,
    display_source: stepState?.status === "solver-backed-post-state" ? "flat-folder-step-state" : "2.5d-inspection-step-preview",
    display_source_status: stepState?.status ?? "inspection-only",
    animation_source_status: stepState?.status === "solver-backed-post-state" ? "solver-backed-pre-post-state" : "inspection-only",
    step_state_path: stepState?.solver_state_path ?? null,
    pre_state_fold_path: stepState?.pre_state_fold_path ?? null,
    input_fold_path: stepState?.input_fold_path ?? null,
    folded_state_path: stepState?.folded_state_path ?? null,
    frame_difference: stepState?.frame_difference ?? null,
    annotations: createStepVisualAnnotations(operation, executorOverlay),
    annotation_legend: stepVisualLegend(),
    executor_overlay: executorOverlay,
    svg: createStepDiagramSvg(preview, operation, step, stepNumber, executorOverlay),
    preview_3d: preview
  };
}

function createStepDiagramSvg(preview, operation, step, stepNumber, executorOverlay) {
  const size = 360;
  const padding = 34;
  const projected = projectPreviewVertices(preview.vertices, size, padding);
  const activeKey = edgeKey(operation.edge);
  const lines = preview.edges.map((edge) => {
    const start = projected.get(edge.vertices[0]);
    const end = projected.get(edge.vertices[1]);
    if (!start || !end) {
      return "";
    }
    const isActive = edgeKey(edge.vertices) === activeKey;
    if (!isActive && edge.assignment !== "B") {
      return "";
    }
    const color = isActive ? "#f97316" : "#0f172a";
    const width = isActive ? 5 : 2.4;
    return `<line x1="${start.x}" y1="${start.y}" x2="${end.x}" y2="${end.y}" stroke="${color}" stroke-width="${width}" stroke-linecap="round"/>`;
  }).filter(Boolean);
  const [a, b] = operation.edge;
  const start = projected.get(a);
  const end = projected.get(b);
  const arrow = start && end ? motionArrow(start, end) : "";
  const midpoint = start && end ? {
    x: round((start.x + end.x) / 2),
    y: round((start.y + end.y) / 2)
  } : null;
  const activeLabel = midpoint
    ? `<text x="${midpoint.x + 10}" y="${midpoint.y - 10}" fill="#9a3412" font-family="Inter, Arial, sans-serif" font-size="11" font-weight="700">${escapeXml(operation.assignment)} fold line</text>`
    : "";
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" role="img" aria-label="${escapeXml(step?.title ?? operation.name)}">`,
    `<rect width="${size}" height="${size}" rx="18" fill="#fffaf0"/>`,
    `<text x="22" y="34" fill="#334155" font-family="Inter, Arial, sans-serif" font-size="18" font-weight="700">Step ${stepNumber}</text>`,
    `<text x="22" y="58" fill="#64748b" font-family="Inter, Arial, sans-serif" font-size="12">orange line = current fold; contact overlay = selected executor</text>`,
    `<g transform="translate(0 20)">`,
    ...lines,
    ...(executorOverlay.svg_elements ?? []),
    arrow,
    activeLabel,
    `</g>`,
    `</svg>`
  ].join("");
}

function createStepVisualAnnotations(operation, executorOverlay) {
  return [
    {
      type: "active-fold-line",
      assignment: operation.assignment,
      edge: operation.edge,
      color: "#f97316",
      meaning: "current step fold line"
    },
    {
      type: "executor-contact-overlay",
      executor_profile: executorOverlay.executor_profile,
      zone_count: executorOverlay.zones.length,
      meaning: "profile-specific contact zones bound to the current fold edge"
    }
  ];
}

function stepVisualLegend() {
  return [
    {
      key: "boundary",
      stroke: "#0f172a",
      meaning: "paper boundary"
    },
    {
      key: "active-fold-line",
      stroke: "#f97316",
      meaning: "current step fold line only"
    },
    {
      key: "executor-contact-overlay",
      meaning: "selected executor contact or blocked precision zone"
    }
  ];
}

function createExecutorOverlay({ preview, projected, operation, executorProfile }) {
  const [a, b] = operation.edge;
  const start = projected.get(a);
  const end = projected.get(b);
  const metadata = getExecutorVisualMetadata(executorProfile);
  if (!start || !end) {
    return {
      type: "foldgen.executor_overlay.v1",
      executor_profile: executorProfile,
      status: "missing-fold-edge-projection",
      geometry_binding: overlayGeometryBinding(operation),
      zones: [],
      unsupported_actions: metadata.unsupported_actions,
      svg_elements: []
    };
  }

  const midpoint = {
    x: round((start.x + end.x) / 2),
    y: round((start.y + end.y) / 2)
  };
  const dx = end.x - start.x;
  const dy = end.y - start.y;
  const angle = Math.atan2(dy, dx) * 180 / Math.PI;
  const length = Math.hypot(dx, dy) || 1;
  const normal = {
    x: -dy / length,
    y: dx / length
  };
  const zoneFactory = overlayZoneFactory({ preview, operation, start, end, midpoint, normal, angle });
  const zones = overlayZonesForProfile(executorProfile, zoneFactory);
  return {
    type: "foldgen.executor_overlay.v1",
    executor_profile: executorProfile,
    status: precisionOverlayStatus(metadata.unsupported_actions),
    geometry_binding: overlayGeometryBinding(operation),
    zones,
    unsupported_actions: metadata.unsupported_actions,
    contact_primitives: metadata.contact_zones,
    svg_elements: zones.map((zone) => zoneToSvg(zone))
  };
}

function overlayZoneFactory({ preview, operation, start, end, midpoint, normal, angle }) {
  const [a, b] = operation.edge;
  const previewVertices = new Map((preview.vertices ?? []).map((vertex) => [vertex.index, vertex]));
  const pointZone = (id, primitive, point, vertexIndex, radius) => ({
    id,
    primitive,
    shape: "circle",
    target: vertexIndex === a ? "fold-line-start" : vertexIndex === b ? "fold-line-end" : "fold-line-center",
    vertex_index: vertexIndex ?? null,
    center_svg: roundPoint(point),
    center_preview: vertexIndex == null ? null : previewPoint(previewVertices.get(vertexIndex)),
    radius,
    color: "#facc15"
  });
  const ellipseZone = (id, primitive, center, rx, ry, color) => ({
    id,
    primitive,
    shape: "ellipse",
    target: "broad-fold-contact-zone",
    vertex_index: null,
    center_svg: roundPoint(center),
    center_preview: null,
    radius_x: rx,
    radius_y: ry,
    rotation_degrees: round(angle),
    color
  });
  const rectZone = (id, primitive, center, width, height) => ({
    id,
    primitive,
    shape: "rotated-rect",
    target: "gripper-jaw-contact",
    vertex_index: null,
    center_svg: roundPoint(center),
    center_preview: null,
    width,
    height,
    rotation_degrees: round(angle),
    color: "#38bdf8"
  });
  return {
    start: (id, primitive, radius = 13) => pointZone(id, primitive, start, a, radius),
    end: (id, primitive, radius = 13) => pointZone(id, primitive, end, b, radius),
    center: (id, primitive, radius = 10) => pointZone(id, primitive, midpoint, null, radius),
    offsetCenter: (distance) => ({
      x: round(midpoint.x + normal.x * distance),
      y: round(midpoint.y + normal.y * distance)
    }),
    ellipseZone,
    rectZone
  };
}

function overlayZonesForProfile(profileId, zone) {
  switch (profileId) {
    case "two-finger-gripper": {
      return [
        zone.rectZone("fixed-jaw-anchor", "hold", zone.offsetCenter(-18), 38, 14),
        zone.rectZone("moving-jaw-fold", "pinch", zone.offsetCenter(18), 38, 14),
        zone.center("short-segment-press", "press", 9)
      ];
    }
    case "cat-paw-profile": {
      return [
        zone.ellipseZone("broad-paw-pad-anchor", "hold", zone.offsetCenter(-20), 42, 26, "#fbbf24"),
        zone.ellipseZone("soft-paw-sweep-zone", "paw-sweep", zone.offsetCenter(22), 38, 24, "#fb923c"),
        zone.center("precision-pinch-blocked", "blocked-precision", 14)
      ];
    }
    case "dog-paw-profile": {
      return [
        zone.ellipseZone("large-paw-brace", "hold", zone.offsetCenter(-24), 56, 34, "#f59e0b"),
        zone.ellipseZone("large-paw-sweep-zone", "paw-sweep", zone.offsetCenter(26), 50, 32, "#fb923c"),
        zone.center("fine-crease-blocked", "blocked-precision", 18)
      ];
    }
    default: {
      return [
        zone.start("fingertip-anchor", "hold", 12),
        zone.end("fingertip-fold", "pinch", 12),
        zone.center("index-finger-crease-press", "press", 9)
      ];
    }
  }
}

function zoneToSvg(zone) {
  const color = zone.color ?? "#facc15";
  const opacity = zone.primitive?.startsWith("blocked") ? "0.28" : "0.46";
  const stroke = zone.primitive?.startsWith("blocked") ? "#b91c1c" : "#92400e";
  if (zone.shape === "ellipse") {
    return `<ellipse cx="${zone.center_svg.x}" cy="${zone.center_svg.y}" rx="${zone.radius_x}" ry="${zone.radius_y}" transform="rotate(${zone.rotation_degrees} ${zone.center_svg.x} ${zone.center_svg.y})" fill="${color}" fill-opacity="${opacity}" stroke="${stroke}" stroke-width="1.6"/>`;
  }
  if (zone.shape === "rotated-rect") {
    return `<rect x="${round(zone.center_svg.x - zone.width / 2)}" y="${round(zone.center_svg.y - zone.height / 2)}" width="${zone.width}" height="${zone.height}" rx="4" transform="rotate(${zone.rotation_degrees} ${zone.center_svg.x} ${zone.center_svg.y})" fill="${color}" fill-opacity="${opacity}" stroke="#0369a1" stroke-width="1.5"/>`;
  }
  return `<circle cx="${zone.center_svg.x}" cy="${zone.center_svg.y}" r="${zone.radius}" fill="${color}" fill-opacity="${opacity}" stroke="${stroke}" stroke-width="1.5"/>`;
}

function precisionOverlayStatus(unsupportedActions) {
  return unsupportedActions.some((action) => /precision|fine|two-point/.test(action))
    ? "precision-actions-blocked-or-fixture-needed"
    : "profile-contact-supported";
}

function overlayGeometryBinding(operation) {
  return {
    coordinate_space: "foldgen.preview.v1",
    operation_id: operation.id,
    assignment: operation.assignment,
    edge: operation.edge
  };
}

function previewPoint(vertex) {
  if (!vertex) {
    return null;
  }
  return {
    x: round(vertex.x),
    y: round(vertex.y),
    z: round(vertex.z ?? 0)
  };
}

function roundPoint(point) {
  return {
    x: round(point.x),
    y: round(point.y)
  };
}

function projectPreviewVertices(vertices, size, padding) {
  const raw = vertices.map((vertex) => ({
    index: vertex.index,
    x: (vertex.x - vertex.y) * 180,
    y: (vertex.x + vertex.y) * 72 - vertex.z * 150
  }));
  const bounds = raw.reduce((result, point) => ({
    minX: Math.min(result.minX, point.x),
    maxX: Math.max(result.maxX, point.x),
    minY: Math.min(result.minY, point.y),
    maxY: Math.max(result.maxY, point.y)
  }), { minX: Infinity, maxX: -Infinity, minY: Infinity, maxY: -Infinity });
  const scale = Math.min(
    (size - padding * 2) / Math.max(bounds.maxX - bounds.minX, 1),
    (size - padding * 2) / Math.max(bounds.maxY - bounds.minY, 1)
  );
  const offsetX = (size - (bounds.maxX - bounds.minX) * scale) / 2 - bounds.minX * scale;
  const offsetY = (size - (bounds.maxY - bounds.minY) * scale) / 2 - bounds.minY * scale;
  return new Map(raw.map((point) => [point.index, {
    x: round(offsetX + point.x * scale),
    y: round(offsetY + point.y * scale)
  }]));
}

function motionArrow(start, end) {
  const dx = end.x - start.x;
  const dy = end.y - start.y;
  const length = Math.hypot(dx, dy) || 1;
  const normal = { x: -dy / length, y: dx / length };
  const from = {
    x: round((start.x + end.x) / 2 - normal.x * 34),
    y: round((start.y + end.y) / 2 - normal.y * 34)
  };
  const to = {
    x: round((start.x + end.x) / 2 + normal.x * 34),
    y: round((start.y + end.y) / 2 + normal.y * 34)
  };
  return [
    `<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#f97316"/></marker></defs>`,
    `<line x1="${from.x}" y1="${from.y}" x2="${to.x}" y2="${to.y}" stroke="#f97316" stroke-width="3" stroke-linecap="round" marker-end="url(#arrow)"/>`
  ].join("");
}

function selectTargets(targets, targetFiles) {
  const byFile = new Map(targets.map((target) => [target.file, target]));
  return targetFiles.map((file) => {
    const target = byFile.get(file);
    if (!target) {
      throw new Error(`${file}: missing target metadata`);
    }
    if (!targetProfiles[file]) {
      throw new Error(`${file}: missing deterministic M2 profile`);
    }
    return target;
  });
}

function candidate(id, name, assignment, edge, score, rationale) {
  const candidateOperation = operation(id, name, assignment, edge, rationale);
  return {
    id,
    score,
    rationale,
    operation: candidateOperation,
    operations: [candidateOperation]
  };
}

function invalidCandidate(id) {
  return candidate(id, "Reject out-of-range exploratory fold", "V", [0, 99], 0, "Records how invalid proposals are kept as pipeline data.");
}

function sequenceCandidate(id, name, operations, score, rationale) {
  return {
    id,
    name,
    score,
    rationale,
    operation: operations[0],
    operations
  };
}

function generatedSequenceCandidate(id, name, operations, score, rationale) {
  return {
    ...sequenceCandidate(id, name, operations, score, rationale),
    origin_kind: "generated-candidate",
    generator: {
      id: "deterministic-local-fold-search-v1",
      version: "v1",
      seed: "phase-16-generated-triangle",
      operation_library_id: "single-edge-collapse-library-v1"
    }
  };
}

function operation(id, name, assignment, edge, rationale) {
  return {
    id,
    name,
    assignment,
    edge,
    instruction: `${name}.`,
    rationale
  };
}

function normalizeOperations(candidateConfig) {
  if (Array.isArray(candidateConfig.operations) && candidateConfig.operations.length > 0) {
    return candidateConfig.operations;
  }
  if (candidateConfig.operation) {
    return [candidateConfig.operation];
  }
  throw new Error(`${candidateConfig.id}: missing operations`);
}

function isGeneratedCandidate(selected) {
  return selected?.origin_kind === "generated-candidate";
}

function generatedStatusForDisplayMode(displayMode) {
  if (displayMode === "completed-usable-generated") {
    return "graduated";
  }
  if (displayMode?.startsWith("blocked-") || displayMode?.startsWith("rejected-")) {
    return "rejected";
  }
  return "not-generated";
}

function createCandidateRecipeArtifact({ target, profile, selected, records }) {
  const generator = selected.generator ?? profile.generator ?? {};
  return {
    type: "foldgen.generated_candidate_recipe.v1",
    case_id: profile.caseId,
    target: {
      name: target.name,
      file: target.file
    },
    generator: {
      id: generator.id ?? profile.generator?.id ?? "deterministic-local-fold-search-v1",
      version: generator.version ?? profile.generator?.version ?? "v1",
      seed: generator.seed ?? profile.generator?.seed ?? null,
      operation_library_id: generator.operation_library_id ?? profile.generator?.operation_library_id ?? null,
      search_policy: profile.generator?.search_policy ?? "candidate cannot graduate without backend, target, step, and executor gates"
    },
    reproducibility_inputs: {
      base_form: profile.baseForm,
      target_features: profile.targetFeatures,
      candidate_count: records.length,
      candidate_ids: records.map((record) => record.candidate_id)
    },
    selected_candidate_id: selected.candidate_id,
    selected_operations: selected.operations.map((operation, index) => ({
      index: index + 1,
      id: operation.id,
      assignment: operation.assignment,
      edge: operation.edge,
      instruction: operation.instruction,
      rationale: operation.rationale
    })),
    graduation_policy: [
      "recipe reproducibility is necessary but not sufficient",
      "backend folded-state artifact must pass",
      "target-match must pass on backend state",
      "every step needs pre/post state replay",
      "executor profile feasibility and overlays must be recorded"
    ]
  };
}

function createCandidateRunArtifact({
  target,
  profile,
  selected,
  selectedValidation,
  communityFoldValidation,
  flatFolderValidation,
  flatFolderState,
  targetMatch,
  stepStates,
  executorOverlays,
  displayDecision,
  artifactPaths
}) {
  const blockers = (displayDecision.gates ?? [])
    .filter((gate) => gate.status !== "passed" && gate.required_for?.includes("completed-usable-generated"))
    .map((gate) => gate.id);
  return {
    type: "foldgen.generated_candidate_run.v1",
    case_id: profile.caseId,
    target: {
      name: target.name,
      file: target.file
    },
    status: displayDecision.display_mode === "completed-usable-generated" ? "graduated" : "rejected",
    display_mode: displayDecision.display_mode,
    selected_candidate_id: selected.candidate_id,
    origin_kind: selected.origin_kind,
    gate_summary: {
      local_fold_validation: selectedValidation?.ok ? "passed" : "failed",
      community_fold_compatibility: communityFoldValidation?.status ?? "not-run",
      flat_folder_validation: flatFolderValidation?.status ?? "not-run",
      backend_state: flatFolderState?.status ?? "not-run",
      target_match: targetMatch?.status ?? "not-run",
      step_replay: stepStates?.status ?? "missing",
      executor_overlays: executorOverlays?.status ?? "missing",
      display_decision: displayDecision.display_mode
    },
    blockers,
    artifact_paths: {
      candidate_recipe: artifactPaths.candidate_recipe,
      candidate_run: artifactPaths.candidate_run,
      derived_fold: artifactPaths.derived_fold,
      folded_state_fold: artifactPaths.folded_state_fold,
      target_match: artifactPaths.target_match,
      step_states: artifactPaths.step_states,
      step_visuals: artifactPaths.step_visuals,
      executor_overlays: artifactPaths.executor_overlays,
      display_decision: artifactPaths.display_decision
    }
  };
}

function buildClaimStatus({ simulatorValid, executorReadable }) {
  return {
    claim_label: simulatorValid && executorReadable
      ? "simulator-valid / executor-readable / embodiment-untested"
      : `${simulatorValid ? "simulator-valid" : "simulator-invalid"} / ${executorReadable ? "executor-readable" : "executor-unreadable"} / embodiment-untested`,
    simulator_valid: simulatorValid,
    executor_readable: executorReadable,
    embodiment_validated: false,
    embodiment_status: "untested",
    final_record_path: null
  };
}

async function createTargetMatchArtifact({ targetPath, foldedStatePath, outputPath, solverState }) {
  if (solverState?.status !== "passed") {
    const blocked = {
      type: "foldgen.target_match.v1",
      status: "blocked",
      metric: "silhouette-iou-v0",
      score: 0,
      threshold: 0.48,
      target_artifact_path: artifactPath(targetPath),
      folded_state_artifact_path: null,
      target_polygon_count: 0,
      folded_polygon_count: 0,
      blocker: "missing-solver-backed-folded-state",
      limitations: ["Target match cannot run without a solver-backed folded-state artifact."]
    };
    await writeJson(outputPath, blocked);
    return blocked;
  }
  return evaluateTargetMatch({ targetSvgPath: targetPath, foldedStatePath, outputPath });
}

function buildResultQuality({ target, externalValidation, completedTarget = false, displayDecision = null }) {
  const flatFolderStatus = externalValidation?.flat_folder?.status ?? "not-run";
  const solverStateStatus = externalValidation?.flat_folder_state?.status ?? "not-run";
  const targetMatchStatus = externalValidation?.target_match?.status ?? "not-run";
  const displayMode = displayDecision?.display_mode ?? "inspection-only";
  const foldabilityStatus = flatFolderStatus === "passed"
    ? "external-solver-passed"
    : flatFolderStatus === "failed"
      ? "external-solver-failed"
      : "external-solver-not-run";
  const previewStatus = solverStateStatus === "passed" ? "solver-backed-folded-state" : "2.5d-inspection-only";
  const targetName = target?.name ?? "target";
  const limitations = [
    "Target silhouette match has not been validated against the reference image."
  ];
  if (previewStatus !== "solver-backed-folded-state") {
    limitations.push("The preview is a deterministic 2.5D inspection rendering, not a physical folding simulation.");
  }
  if (foldabilityStatus === "external-solver-failed") {
    limitations.push("Flat-Folder did not validate this crease pattern as a solver-successful fold.");
  }
  if (solverStateStatus !== "passed") {
    limitations.push("No solver-backed folded-state artifact is available for completed-target display.");
  }
  if (solverStateStatus === "passed" && targetMatchStatus !== "passed") {
    limitations.push("Solver-backed folded state does not pass the target silhouette gate.");
  }
  if (displayDecision?.display_mode === "completed-3d-partial-walkthrough") {
    limitations.push("Final folded-state target passes, but at least one walkthrough step is not solver-backed.");
  }
  if (displayDecision?.display_mode === "completed-usable-generated") {
    limitations.push("This is a generated candidate graduation, not a known-good tutorial fixture or physical embodiment record.");
  }
  if (displayDecision?.display_mode === "blocked-executor") {
    limitations.push("Geometry gates pass, but selected executor overlay evidence is incomplete or unsupported.");
  }
  return {
    target_match_status: targetMatchQualityStatus(targetMatchStatus, solverStateStatus),
    foldability_status: foldabilityStatus,
    preview_status: previewStatus,
    display_mode: displayMode,
    display_status: displayDecision?.display_status ?? "inspection-only",
    physical_result_status: "not-proven",
    summary: resultQualitySummary({ targetName, completedTarget, displayDecision }),
    limitations
  };
}

function resultQualitySummary({ targetName, completedTarget, displayDecision }) {
  if (displayDecision?.display_mode === "completed-usable-generated") {
    return `${targetName} is a generated candidate that passed backend folded-state geometry, target match, complete step replay, and executor feasibility gates.`;
  }
  if (displayDecision?.display_mode === "completed-usable") {
    return `${targetName} has solver-backed folded-state geometry, passes target match, and has complete step-state plus executor overlay evidence.`;
  }
  if (displayDecision?.display_mode === "completed-3d-partial-walkthrough") {
    return `${targetName} has solver-backed folded-state geometry and passes target match, but is not a completed usable walkthrough yet.`;
  }
  if (completedTarget) {
    return `${targetName} has solver-backed folded-state geometry and passes the silhouette target-match gate.`;
  }
  return `${targetName} is blocked from completed-target display until solver-backed folded-state geometry exists.`;
}

function summarizeDisplayDecision(displayDecision) {
  return {
    type: displayDecision.type,
    display_mode: displayDecision.display_mode,
    display_status: displayDecision.display_status,
    target_complete: displayDecision.target_complete,
    completed_usable: displayDecision.completed_usable,
    generated_usable: displayDecision.generated_usable ?? false,
    safe_to_render_completed_card: displayDecision.safe_to_render_completed_card,
    safe_to_render_3d_preview: displayDecision.safe_to_render_3d_preview,
    render_source: displayDecision.render_source,
    weakest_failed_gate: displayDecision.weakest_failed_gate,
    summary: displayDecision.summary
  };
}

function targetMatchQualityStatus(targetMatchStatus, solverStateStatus) {
  if (targetMatchStatus === "passed") {
    return "target-match-passed";
  }
  if (targetMatchStatus === "failed") {
    return "target-match-failed";
  }
  if (solverStateStatus !== "passed") {
    return "target-match-blocked-by-solver";
  }
  return "target-match-unscored";
}

function summarizeSolverState(result) {
  return {
    adapter_id: result.adapter_id,
    tool_name: result.tool_name,
    tool_version: result.tool_version,
    status: result.status,
    result_path: result.output_artifact_paths?.[0] ?? null,
    folded_state_path: result.output_artifact_paths?.[1] ?? null,
    errors: result.errors ?? [],
    warnings: result.warnings ?? [],
    claim_effect: result.claim_effect,
    state_count: result.state_count ?? 0,
    component_count: result.component_count ?? 0,
    face_order_count: result.face_order_count ?? 0,
    folded_vertex_count: result.folded_vertex_count ?? 0,
    conflict: result.conflict ?? null
  };
}

function missingSolverState() {
  return {
    adapter_id: "flat-folder-state",
    tool_name: "Flat-Folder",
    tool_version: "unknown",
    status: "not-run",
    result_path: null,
    folded_state_path: null,
    errors: [],
    warnings: ["solver-state adapter has not run for this case"],
    claim_effect: "no solver-backed folded-state claim",
    state_count: 0,
    component_count: 0,
    face_order_count: 0,
    folded_vertex_count: 0,
    conflict: null
  };
}

function summarizeTargetMatch(result) {
  return {
    adapter_id: "target-match",
    tool_name: "foldgen silhouette IoU",
    tool_version: "v0",
    status: result.status,
    result_path: result.output_artifact_path ?? null,
    score: result.score ?? 0,
    threshold: result.threshold ?? null,
    metric: result.metric ?? "unknown",
    blocker: result.blocker ?? null,
    claim_effect: result.status === "passed"
      ? "supports target-complete display for this solver-backed folded state"
      : "blocks target-complete display"
  };
}

function summarizeStepStates(result) {
  return {
    adapter_id: "step-states",
    tool_name: "Flat-Folder per-step post-state extraction",
    tool_version: "v0",
    status: result.status,
    result_path: result.output_path,
    step_count: result.step_count,
    solver_backed_step_count: result.solver_backed_step_count,
    inspection_only_step_count: result.inspection_only_step_count,
    claim_effect: result.status === "complete"
      ? "all walkthrough steps have solver-backed post-state artifacts"
      : result.status === "partial"
        ? "some walkthrough steps have solver-backed post-state artifacts; remaining steps are inspection-only"
        : "no solver-backed walkthrough step states"
  };
}

function summarizeExecutorOverlays(result) {
  return {
    adapter_id: "executor-overlays",
    tool_name: "foldgen executor overlay artifacts",
    tool_version: "v1",
    status: result.status,
    result_path: result.output_path,
    profile_count: result.profile_count,
    step_count: result.step_count,
    claim_effect: result.status === "complete"
      ? "all executor profiles have geometry-linked overlay artifacts for every step"
      : "missing executor overlay artifacts block completed-usable display"
  };
}

function missingExecutorOverlays() {
  return {
    adapter_id: "executor-overlays",
    tool_name: "foldgen executor overlay artifacts",
    tool_version: "v1",
    status: "missing",
    result_path: null,
    profile_count: 0,
    step_count: 0,
    claim_effect: "executor overlay artifact generation did not run"
  };
}

function missingStepStates() {
  return {
    adapter_id: "step-states",
    tool_name: "Flat-Folder per-step post-state extraction",
    tool_version: "v0",
    status: "missing",
    result_path: null,
    step_count: 0,
    solver_backed_step_count: 0,
    inspection_only_step_count: 0,
    claim_effect: "step-state extraction did not run"
  };
}

function missingTargetMatch() {
  return {
    adapter_id: "target-match",
    tool_name: "foldgen silhouette IoU",
    tool_version: "v0",
    status: "not-run",
    result_path: null,
    score: 0,
    threshold: null,
    metric: "unknown",
    blocker: "target-match-not-run",
    claim_effect: "blocks target-complete display"
  };
}

function solverBlockedReason({ flatFolderValidation, flatFolderState, targetMatch }) {
  if (flatFolderValidation?.status !== "passed") {
    return "flat-folder-validation-failed";
  }
  if (flatFolderState?.status !== "passed") {
    return "solver-backed-folded-state-missing";
  }
  if (targetMatch?.status !== "passed") {
    return targetMatch?.status === "failed" ? "target-match-failed" : "target-match-missing";
  }
  return "completed-target-gate-failed";
}

async function writeJson(path, value) {
  await writeFile(path, `${stableStringify(value, 2)}\n`, "utf8");
}

function artifactPath(path) {
  return toPosix(relative(process.cwd(), path));
}

function toPosix(path) {
  return path.split("\\").join("/");
}

function colorForAssignment(assignment) {
  switch (assignment) {
    case "B":
      return "#0f172a";
    case "M":
      return "#dc2626";
    case "V":
      return "#2563eb";
    case "F":
      return "#64748b";
    default:
      return "#94a3b8";
  }
}

function referenceEdgeColor(assignment) {
  return assignment === "B" ? "#0f172a" : "#94a3b8";
}

function edgeKey(edge) {
  return [...edge].sort((a, b) => a - b).join(":");
}

function round(value) {
  return Number(value.toFixed(3));
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function cloneJson(value) {
  return JSON.parse(JSON.stringify(value));
}
